### ISSUE TITLE
add screenshot of a catbot nblast call to readme?

### ISSUE THREAD

**Issue by jefferis** [flyconnectome/catbot#5]

**Comment by schlegelp** [comment]
<img width="1106" alt="screen shot 2017-02-24 at 15 05 13" src="https://cloud.githubusercontent.com/assets/7161148/23308336/ce5682be-faa2-11e6-9400-6bdb369f1b15.png">

**Comment by schlegelp** [comment]
Have a look at the current readme: Is this what you had in mind?

**Comment by jefferis** [comment]
That looks good. Only thing might have been to include snapshot of the nblast result, so that people can get a feel for what it looks like.

**Comment by schlegelp** [comment]
<img width="575" alt="screen shot 2017-03-03 at 15 45 22" src="https://cloud.githubusercontent.com/assets/7161148/23557599/76695c44-0028-11e7-94dd-a9bd6edbb746.png">
